name: Build and deploy ASP.Net Core app to Azure Web App - TaskManager

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: mytaskmanagerappservices
  AZURE_WEBAPP_PACKAGE_PATH: TaskManager/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_82D214FB6D02423FA5031BE9F887AEA3 }}
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.301
  WORKING_DIRECTORY_BACKEND: backend
  WORKING_DIRECTORY_FRONTEND: frontend
  NAME: TaskManager/TaskManager.csproj
  NODE_VERSION: '14.x'

jobs:
  build:
    runs-on: windows-latest

    steps:  
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build "${{ env.WORKING_DIRECTORY_BACKEND }}" --configuration ${{ env.CONFIGURATION }}

      - name: dotnet publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY_BACKEND }}/${{ env.NAME }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
          
      - name: copy files
        uses: OnizukaJS/copycat-action@v3
        with:
          personal_token: ${{ env.PERSONAL_TOKEN }}
          src_path: frontend/build
          dst_owner: OnizukaJS
          dst_repo_name: backend/TaskManager/wwwroot
          dst_branch: master
          src_branch: maste
    
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
