name: Build and deploy ASP.Net Core app to Azure Web App - TaskManager

on:
  push:
    branches:
      - master

env:
  APP_NAME: TaskManager
  AZURE_WEBAPP_NAME: mytaskmanagerappservices
  AZURE_WEBAPP_PACKAGE_PATH: TaskManager/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_82D214FB6D02423FA5031BE9F887AEA3 }}
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.301
  WORKING_DIRECTORY_BACKEND: backend
  WORKING_DIRECTORY_FRONTEND: frontend
  NAME: TaskManager/TaskManager.csproj
  NODE_VERSION: '14.x'
  ROOT: wwwroot

jobs:
  build:
    runs-on: windows-latest

    steps:  
      - uses: actions/checkout@v2
      
      - name: npm install, build
        shell: powershell
        run: |
          npm install
          npm run build
        
      - name: Delete wwwroot folder
        shell: powershell
        run: |
          Remove-Item -Path "${{ env.WORKING_DIRECTORY_BACKEND }}/${{ env.APP_NAME }}/${{ env.ROOT }}" -Force -Recurse
          
      - name: Copy paste build folder to wwwroot
        shell: powershell
        run: |
          Copy-Item -Path "${{ env.WORKING_DIRECTORY_FRONTEND }}/build" -Destination "${{ env.WORKING_DIRECTORY_BACKEND }}/${{ env.APP_NAME }}/${{ env.ROOT }}" -Recurse

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build "${{ env.WORKING_DIRECTORY_BACKEND }}" --configuration ${{ env.CONFIGURATION }}

      - name: dotnet publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY_BACKEND }}/${{ env.NAME }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
