name: Build and deploy Node.js app to Azure web App

on:
  push:
    branches:
      - master
    paths:
      - frontend/**

  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: mytaskmanagerappservices
  AZURE_WEBAPP_PACKAGE_PATH: TaskManager/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE_FRONTEND }}
  NODE_VERSION: '14.x'
  WORKING_DIRECTORY: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        npm install
        npm run build --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: ${{ env.WORKING_DIRECTORY }}/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: "Production"
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
